version: '3'
services:

  mysql:
    image: mysql:5.6
    container_name: team4_mysql
    hostname: team4_mysql_host
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - "db-data:/var/lib/mysql"
  api:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: team4_api  
    command: go run server.go
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080

volumes:
  db-data:
    driver: local      